### ISSUE TITLE
Does this plugin work with Relevanssi?

### ISSUE THREAD

**Issue by shtefcs** [wp-media/wp-rocket-helpers#12]
Hi, I am wondering if this plugin works with [Relevanssi](https://www.relevanssi.com) plugin ?

I want to cache results page of example.com/?=search+term. Is it possible ?

**Comment by arunbasillal** [comment]
@shtefcs I am assuming you are asking about WP Rocket plugin? http://wp-rocket.me

To answer your question, you can use the `rocket_cache_search` filter to do this. https://github.com/wp-media/wp-rocket/blob/33578f0dd568819d3e5912e38cafb9d51d5964d7/inc/front/process.php#L324

Please use our support channels for faster responses in the future. The issues are not tracked and I came across this by chance - https://wp-rocket.me/support/
