### ISSUE TITLE
Proposed Fix for Rocket Lazyload helpers

### ISSUE THREAD

**Issue by cborchert** [wp-media/wp-rocket-helpers#15]
In the file `wp-rocket-helpers/lazyload/wp-rocket-lazyload-youtube-preview-image/wp-rocket-lazyload-youtube-preview-image.php/` there is a bug where the helper function is referencing the incorrect filter.

The code is currently:

```
function resolution( $thumbnail_resolution ) {

	$thumbnail_resolution = WPROCKETHELPERS_LL_YT_PREVIEW_RESOLUTION;

	return $thumbnail_resolution;
}
add_filter( 'rocket_youtube_thumbnail_resolution', __NAMESPACE__ . '\resolution' );
```

The filter name is actually `rocket_lazyload_youtube_thumbnail_resolution` so the code should be:
```
function resolution( $thumbnail_resolution ) {

	$thumbnail_resolution = WPROCKETHELPERS_LL_YT_PREVIEW_RESOLUTION;

	return $thumbnail_resolution;
}
add_filter( 'rocket_lazyload_youtube_thumbnail_resolution', __NAMESPACE__ . '\resolution' );
```

I would be willing to create a pull request to fix this, but I don't see your procedures for doing so.

**Comment by arunbasillal** [comment]
Hello @cborchert 

Thanks for the feedback. Here is the filter `rocket_youtube_thumbnail_resolution`

https://github.com/wp-media/wp-rocket/blob/6b432e03e4bc076aa811b486b703ec9abc21b253/inc/front/lazyload.php#L97

I am wondering where you found the filter `rocket_lazyload_youtube_thumbnail_resolution`. A search for it returns empty - https://github.com/wp-media/wp-rocket/search?q=rocket_lazyload_youtube_thumbnail_resolution&unscoped_q=rocket_lazyload_youtube_thumbnail_resolution
