### ISSUE TITLE
Plz Update

### ISSUE THREAD

**Issue by eduardogt** [wp-media/wp-rocket-helpers#16]
The plugin no longer works in versions of wp-rocket 3.2.4

**Comment by ernee** [comment]
Hi @eduardogt !

Which helper plugin are you referring to? 

Thanks!

**Comment by eduardogt** [comment]
Hello to this: https://github.com/wp-media/wp-rocket-helpers/tree/master/various/wp-rocket-custom-preload-intervals

**Comment by eduardogt** [comment]
PRELOAD_INTERVAL_IN_SECONDS deprecated

**Comment by arunbasillal** [comment]
@eduardogt I just tested this helper and it worked correctly. 

I verified by logging the value when we use it, i.e. here: https://github.com/wp-media/wp-rocket/blob/82680e5c8884c4c08bf547f4d4802d4b7d8cb93f/inc/classes/preload/class-full-process.php#L69

If you still face issue, please raise a support ticket: https://wp-rocket.me/support
