### ISSUE TITLE
Common Cache with Custom Cookie

### ISSUE THREAD

**Issue by Mohaftig** [wp-media/wp-rocket-helpers#17]
Hello,

I was trying to get a seperate cache for <del>users</del> visitors with a custom cookie. With [WP Rocket | Common Cache For Logged-in Users](https://github.com/wp-media/wp-rocket-helpers/tree/master/cache/wp-rocket-cache-common-cache-loggedin) and following [this instructions](https://docs.wp-rocket.me/article/313-user-cache). But maybe I misunderstood the purpose.

Do <del>users</del> visitors still have to be logged in as user in WordPress, in order to work with custom cookies?

- I checked the browser console and the custom cookie was placed
- Seperate static cache files were **sometimes** present, with different content like intended
- But I could only see the "normal" cache in my browsers. (Desktop Firefox and Chrome).

**Comment by arunbasillal** [comment]
Hi @Mohaftig - this isn't a support forum. Please submit a ticket here so we can help you:
https://wp-rocket.me/support, or from the plugin interface.
