### ISSUE TITLE
Disable on certain pages

### ISSUE THREAD

**Issue by dkeys222** [wp-media/wp-rocket-helpers#23]
Does this have the ability to block cache on certain pages? Because about 95% of my pages I want to cache and optimize. The other 5% I just want to optimize.

Can this please be made possible??

**Comment by arunbasillal** [comment]
Hello @dkeys222 

Currently, there is no easy way to exclude a page from caching while still keeping other optimizations. In fact, we considered this feature, but our initial study suggests no major gains from having just the optimizations alone. 

I hope you know this already, here is how to exclude pages from cache - https://docs.wp-rocket.me/article/54-exclude-pages-from-the-cache

Please note that this is not a support forum, please open a support ticket here for additional questions - https://wp-rocket.me/support/

Thanks
