### ISSUE TITLE
no-cache-purge plugin not working when update post or page

### ISSUE THREAD

**Issue by rchen9012** [wp-media/wp-rocket-helpers#27]
wordpress 5.3.2, wp-rocket 3.5.2,  Disable Cache Clearing plugin not working when I update page or post, all cache file purged.

**Comment by naurelijs** [comment]
Same, not working.. im getting php errors

**Comment by girlie** [comment]
Please go here and open a support ticket so someone can help you with this:
https://wp-rocket.me/support/

**Comment by weilingwei** [comment]
Same, not working.. im getting php errors
