### ISSUE TITLE
Recently viewed products don't display at all

### ISSUE THREAD

**Issue by marknokes** [wp-media/wp-rocket-helpers#29]
After enabling the plugin, no longer do I get a cached version of one or two products per page, I get no recently viewed products. WP Version 5.4, WP Rocket Version 3.5.4

**Comment by arunbasillal** [comment]
Please go here and open a support ticket so someone can help you with this:
https://wp-rocket.me/support/

This repository is not intended for product support but for helper plugins. The name is a bit confusing, sorry about that.
