### ISSUE TITLE
Avoid message WP Rocket: One or more plugins have been enabled ... when active

### ISSUE THREAD

**Issue by thegulshankumar** [wp-media/wp-rocket-helpers#33]
WP Rocket: One or more plugins have been enabled or disabled, clear the cache if they affect the front end of your site.

If Caching is disabled, then this message should also not appear at all.

**Comment by LSB-Web-Design** [comment]
I also find this quite annoying. Is there any progress on this?

**Comment by girlie** [comment]
Hi, we aren't able to provide WP Rocket support via GitHub; please visit our [help center](https://wp-rocket.me/support/) instead (where you'll be able to sign into your account and submit a request to the team, assuming you don't find the answer in the documentation).
