### ISSUE TITLE
Not working on latest WPR release  (3.7.5)

### ISSUE THREAD

**Issue by henryschmieder** [wp-media/wp-rocket-helpers#38]
Has this been tested with the recent main plugin release cycles? It does not seem to work with 3.7.5

**Comment by laurentdebricon** [comment]
i confirm. it's a pain because it could be useful like having a 'developer mode' in production.
Looking for a fix

**Comment by ChrisTec-Dev** [comment]
I also confirm, the plugin doesn't seem to work with WP Rocket 3.8.4. Changes made to the entire empty cache pages with DIVI.

**Comment by girlie** [comment]
Hi everyone. We don't provide support here on this repo, so if you're a customer needing help with one of these helper plugins, please go through our Help Center instead:

https://wp-rocket.me/support/
