### ISSUE TITLE
Allow wp-json requests through htaccess without adding trailing slash

### ISSUE THREAD

**Issue by devonto** [wp-media/wp-rocket-helpers#40]
The snippet at [https://github.com/wp-media/wp-rocket-helpers/tree/master/htaccess/wp-rocket-htaccess-trailing-slash/](https://github.com/wp-media/wp-rocket-helpers/tree/master/htaccess/wp-rocket-htaccess-trailing-slash/) to force trailing slashes should not modify any wp-json requests.

Adding the below code to the file would be suggested:

`$redirection .= 'RewriteCond %{REQUEST_URI} !^/wp-json/' . PHP_EOL;`

**Comment by alfonso100** [comment]
Hi @devonto thank you for your valuable suggestion! 
sorry for the delay in getting back, we've added the suggested code to the helper, and it works perfectly fine.
