### ISSUE TITLE
SEO issue with Enforce Trailing Slash on URLs

### ISSUE THREAD

**Issue by plastiktasche** [wp-media/wp-rocket-helpers#5]
When the URL  is a file like .jpg, .pdf or .xml the slash is also put at the end of the URL.

Example:

```
example.com/wp-content/uploads/myimage.jpg
```

is changed into

```
example.com/wp-content/uploads/myimage.jpg/
```

The backlinks which point to these files are broken because of the added slash at the end. I noticed this by following the backlinks pointing to these files (404 not found). This is a big SEO-issue if you have a lot of backlinks pointing to your files.

**Comment by arunbasillal** [comment]
Hello @plastiktasche 

Is this an issue you noticed with WP Rocket? If you are a customer, please open a support ticket with links to your website because this is not the expected behavior. 

Please let me know where you noticed this. Best regards.

**Comment by webtrainingwheels** [comment]
@plastiktasche I answered your support ticket earlier today with a proposed fix. I can't reproduce your issue regarding .jpg so would like your confirmation on that. 

@glueckpress @arunbasillal 
https://secure.helpscout.net/conversation/554514216/64325?folderId=377611
