### ISSUE TITLE
WPR Dbugger preload no progress

### ISSUE THREAD

**Issue by mmprep** [wp-media/wp-rocket-helpers#54]
Please check if [D-bugger](https://github.com/wp-media/wp-rocket-helpers/tree/master/various/wp-rocket-dbugger) helper is working correctly.

The Preload tab [does not show any change in preload progress](https://ibb.co/6Js5w4W) even after many hours of WP Rocket. At the same time the cache size on disk is growing properly.

To clarify, I changed the default settings through the Custom Sitemap Preload Intervals and Change Preload Parameters helpers.

Tell me, on the RUCSS tab when you click _Clear FAILED_ button the information about the failed tasks is cleared, but after a while are they put back in the queue for pending?

**Comment by alfonso100** [comment]
Hi @mmprep thanmk you for reporting this. 
Can you please open a support ticket, one of my teammates will check this for you.

thanks!
