### ISSUE TITLE
Excluding doesn't seem to work

### ISSUE THREAD

**Issue by TomberWolf** [wp-media/wp-rocket-helpers#7]
Hey Rocket Team,

I tried to use this addon to exclude Easy FancyBox because it doesn't work with this setting.
I just want to make sure that I understand it correctly.

Here are my settings:

[wp-rocket-static-exclude-defer-js.php.txt](https://github.com/wp-media/wp-rocket-helpers/files/1922352/wp-rocket-static-exclude-defer-js.php.txt)

(.txt extension is just to attach the php file because github doesn't allow .php files)

**Comment by TomberWolf** [comment]
I think so, because the lightbox isn't working.
I will give an additional try and let you know. If it won't work I will open a ticket at wp-rocket.me.

**Comment by arunbasillal** [comment]
Sounds good, please include a link to this GitHub issue so we can keep track of the conversation :)
