### ISSUE TITLE
Disable All Automatic Cache Clearing does not seem to work

### ISSUE THREAD

**Issue by Dibbyo456** [wp-media/wp-rocket-helpers#8]
Sometimes I'm losing cache files. I have set 10 days to keep cache. But still sometimes I'm loosing cache even I have no automatic cache clear installed.

**Comment by arunbasillal** [comment]
Hey @Dibbyo456 

WP Rocket clears cache not just at the end of cache lifespan, but at other times too. Please refer this: https://docs.wp-rocket.me/article/78-how-often-is-the-cache-updated#full-cache-deletion

If you think something unnatural is still going on, please open a support ticket: https://wp-rocket.me/support/

Best regards.
