### ISSUE TITLE
Choose indvidual pages?

### ISSUE THREAD

**Issue by ehus** [wp-media/wp-rocket-helpers#9]
Hi,

We have a site with a 2 user generated pages. Can we apply this action on a per-page basis?

Thanks!

**Comment by arunbasillal** [comment]
Hello @ehus 

Which helper plugin / action are we talking about here?

**Comment by ehus** [comment]
Hi Arun!

Thanks for the response, you provided me a fix yesterday! 

Full Code: http://snippi.com/s/rzqigxi

`function rocket_helper_do_not_generate_cache_for_page( $filter ) {
	
	/**
	 * Change the ID (2 in this example) to the page ID you want to exclude.
	 * For multiple ID's add all of them to the array as a comma seperated list. eg: array( 2, 4, 8 )
	 **/
	if ( function_exists( 'is_page' ) && ! is_page( array( 2 ) ) ) {
		return $filter;
	}
	
	return false;
}
add_filter( 'do_rocket_generate_caching_files', 'rocket_helper_do_not_generate_cache_for_page' );`

Cheers!

**Comment by arunbasillal** [comment]
Glad to hear @ehus
